# Generated by Django 4.2.10 on 2025-06-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rentalvideo_rentalpostimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='category',
            field=models.CharField(choices=[('phongtro', 'Phòng trọ, nhà trọ'), ('nhanguyencan', 'Nhà thuê nguyên căn'), ('canho', 'Cho thuê căn hộ'), ('canho_mini', 'Cho thuê căn hộ mini'), ('canho_dichvu', 'Cho thuê căn hộ dịch vụ'), ('oghep', 'Tìm người ở ghép'), ('matbang', 'Cho thuê mặt bằng + Văn phòng')], default='phongtro', max_length=50),
        ),
    ]
