# Generated by Django 4.2.10 on 2025-08-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rentalpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('owner', 'Chủ trọ')], default='customer', max_length=20),
        ),
    ]
