# Generated by Django 4.2.10 on 2025-08-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_customerprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='role',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
