# Generated by Django 4.2.10 on 2025-08-18 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_customerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('owner', 'Chủ trọ')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
