# Generated by Django 4.2.10 on 2025-08-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_customerprofile_created_at_customerprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
