# Generated by Django 4.2.10 on 2025-08-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_district_province_ward_district_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
