# Generated by Django 4.2.10 on 2025-08-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_ward_district_delete_district_delete_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='district_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='district_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='province_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='province_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='ward_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='ward_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
