# Generated by Django 4.2.10 on 2025-08-18 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0012_rentalpost_district_code_rentalpost_district_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpost',
            name='address',
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='address_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='full_address',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='category',
            field=models.CharField(choices=[('phongtro', 'Phòng trọ, nhà trọ'), ('nhanguyencan', 'Nhà thuê nguyên căn'), ('canho', 'Cho thuê căn hộ'), ('canho_mini', 'Cho thuê căn hộ mini'), ('canho_dichvu', 'Cho thuê căn hộ dịch vụ'), ('oghep', 'Tìm người ở ghép'), ('matbang', 'Cho thuê mặt bằng / Văn phòng')], default='phongtro', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalvideo',
            name='video',
            field=models.FileField(upload_to='rental_videos/'),
        ),
    ]
