# Generated by Django 4.2.10 on 2025-08-18 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0013_remove_rentalpost_address_rentalpost_address_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpost',
            name='address_detail',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='district_code',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='features',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='province_code',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='province_name',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='ward_code',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='ward_name',
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='category',
            field=models.CharField(choices=[('phongtro', 'Phòng trọ, nhà trọ'), ('nhanguyencan', 'Nhà thuê nguyên căn'), ('canho', 'Cho thuê căn hộ'), ('canho_mini', 'Cho thuê căn hộ mini'), ('canho_dichvu', 'Cho thuê căn hộ dịch vụ'), ('oghep', 'Tìm người ở ghép'), ('matbang', 'Cho thuê mặt bằng + Văn phòng')], default='phongtro', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentalpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalvideo',
            name='video',
            field=models.FileField(upload_to='uploads/videos/'),
        ),
    ]
