# Generated by Django 4.2.10 on 2025-08-18 16:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_rentalpost_address_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('day_du_noi_that', 'Đầy đủ nội thất'), ('co_may_lanh', 'Có máy lạnh'), ('co_thang_may', 'Có thang máy'), ('bao_ve_24_24', 'Có bảo vệ 24/24'), ('co_gac', 'Có gác'), ('co_may_giat', 'Có máy giặt'), ('khong_chung_chu', 'Không chung chủ'), ('co_ham_de_xe', 'Có hầm để xe'), ('co_ke_bep', 'Có kệ bếp'), ('co_tu_lanh', 'Có tủ lạnh'), ('gio_giac_tu_do', 'Giờ giấc tự do')], max_length=137, null=True),
        ),
    ]
