# Generated by Django 4.2.10 on 2025-08-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_rentalpost_district_rentalpost_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpost',
            name='district',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='province',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='street',
        ),
        migrations.RemoveField(
            model_name='rentalpost',
            name='ward',
        ),
    ]
