# Generated by Django 4.2.10 on 2025-08-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_district_province_rentalpost_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
