# Generated by Django 4.2.10 on 2025-09-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_chatthread_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatthread',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='chatthread',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='chatthread',
            name='post',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatThread',
        ),
    ]
