# Generated by Django 4.2.10 on 2025-09-10 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0024_remove_chatthread_guest_remove_chatthread_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpost',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('day_du_noi_that', 'Đầy đủ nội thất'), ('co_may_lanh', 'Có máy lạnh'), ('co_thang_may', 'Có thang máy'), ('bao_ve_24_24', 'Có bảo vệ 24/24'), ('co_gac', 'Có gác'), ('co_may_giat', 'Có máy giặt'), ('khong_chung_chu', 'Không chung chủ'), ('co_ham_de_xe', 'Có hầm để xe'), ('co_ke_bep', 'Có kệ bếp'), ('co_tu_lanh', 'Có tủ lạnh'), ('gio_giac_tu_do', 'Giờ giấc tự do')], default=[], max_length=137),
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_chats', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_chats', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='website.rentalpost')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('post', 'guest', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='website.chatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
