# Generated by Django 4.2.10 on 2025-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_chatmessage_deleted_at_chatmessage_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='deleted_by_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='deleted_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
