# Generated by Django 4.2.10 on 2025-09-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_chatthread_deleted_by_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatthread',
            name='deleted_by_guest',
        ),
        migrations.RemoveField(
            model_name='chatthread',
            name='deleted_by_owner',
        ),
    ]
