# Generated by Django 4.2.10 on 2025-09-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_sitevisit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sitevisit',
            new_name='website_sit_created_3d2d07_idx',
            old_name='website_sit_created_abc123',
        ),
    ]
