# Generated by Django 4.2.10 on 2025-09-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_article_suggestedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='ai_checked_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian AI kiểm tra', null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='ai_confidence',
            field=models.FloatField(blank=True, help_text='Độ tin cậy của AI (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='ai_flagged',
            field=models.BooleanField(default=False, help_text='AI đã gắn cờ nội dung đáng ngờ'),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='ai_ml_confidence',
            field=models.FloatField(blank=True, help_text='Độ tin cậy ML', null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='ai_ml_prediction',
            field=models.IntegerField(blank=True, help_text='Kết quả ML prediction', null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='ai_reason',
            field=models.TextField(blank=True, help_text='Lý do AI gắn cờ'),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='ai_rule_score',
            field=models.FloatField(blank=True, help_text='Điểm từ rule-based check', null=True),
        ),
    ]
