# Generated by Django 4.2.10 on 2025-09-23 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0036_rentalpost_ai_checked_at_rentalpost_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
