# Generated by Django 4.2.10 on 2025-09-23 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0038_deletionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionlog',
            name='deleted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deletionlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_deletions', to=settings.AUTH_USER_MODEL),
        ),
    ]
