# Generated by Django 4.2.10 on 2025-09-28 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0040_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='website.rentalpost'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, help_text='Số dư (VNĐ)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RechargeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Số tiền nạp (VNĐ)', max_digits=15)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Chuyển khoản ngân hàng'), ('momo', 'Ví MoMo'), ('zalopay', 'Ví ZaloPay'), ('vnpay', 'VNPay'), ('cash', 'Tiền mặt')], default='bank_transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('completed', 'Thành công'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(help_text='Mã giao dịch', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, help_text='Ghi chú của admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
