# Generated by Django 4.2.10 on 2025-09-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_alter_chatthread_post_wallet_rechargetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargetransaction',
            name='momo_order_id',
            field=models.CharField(blank=True, help_text='Order ID trả về từ MoMo sandbox/production', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='rechargetransaction',
            name='raw_response',
            field=models.JSONField(blank=True, help_text='Lưu payload trả về từ cổng thanh toán', null=True),
        ),
    ]
