# Generated by Django 4.2.10 on 2025-10-10 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0042_rechargetransaction_momo_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargetransaction',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Ví MoMo'), ('vnpay', 'VNPay'), ('cash', 'Tiền mặt')], default='bank_transfer', max_length=20),
        ),
        migrations.CreateModel(
            name='PostingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(choices=[('vip_noibat', 'Tin VIP Nổi Bật'), ('vip1', 'Tin VIP 1'), ('vip2', 'Tin VIP 2'), ('vip3', 'Tin VIP 3')], max_length=32)),
                ('duration_days', models.PositiveIntegerField(default=3, help_text='Số ngày hiệu lực của gói')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Số tiền đã trừ (VNĐ)', max_digits=12)),
                ('status', models.CharField(choices=[('completed', 'Hoàn tất'), ('failed', 'Thất bại')], default='completed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
