# Generated by Django 4.2.10 on 2025-10-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_alter_rechargetransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostingOrder',
        ),
    ]
