# Generated by Django 4.2.10 on 2025-10-12 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_vipsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', 'Tin có dấu hiệu lừa đảo'), ('duplicate', 'Tin trùng lặp nội dung'), ('unreachable', 'Không liên hệ được chủ tin đăng'), ('incorrect', 'Thông tin không đúng thực tế (giá, diện tích, hình ảnh...)'), ('other', 'Lý do khác')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='website.rentalpost')),
            ],
        ),
    ]
