# Generated by Django 4.2.10 on 2025-10-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
