# Generated by Django 4.2.10 on 2025-10-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_delete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='renewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
