# Generated by Django 4.2.10 on 2025-10-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_rentalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='cancel_request_status',
            field=models.CharField(choices=[('none', 'Không có yêu cầu'), ('waiting', 'Chờ xác nhận hủy'), ('approved', 'Đã xác nhận hủy'), ('rejected', 'Từ chối hủy')], default='none', max_length=16),
        ),
    ]
