# Generated by Django 4.2.10 on 2025-10-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_rentalrequest_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentalrequest',
            unique_together=set(),
        ),
    ]
