# Generated by Django 4.2.10 on 2025-10-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_alter_rentalrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Số tiền đặt cọc (VNĐ)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='deposit_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='deposit_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='deposit_status',
            field=models.CharField(choices=[('none', 'Không yêu cầu'), ('requested', 'Đã yêu cầu đặt cọc'), ('paid', 'Đã đặt cọc'), ('cancelled', 'Khách hủy đặt cọc'), ('waived', 'Không cần đặt cọc')], default='none', max_length=12),
        ),
    ]
