# Generated by Django 4.2.10 on 2025-10-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_rentalrequest_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Số điện thoại liên hệ', max_length=15, null=True),
        ),
    ]
