# Generated by Django 4.2.10 on 2025-10-29 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_rentalpost_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100, verbose_name='Họ tên người báo cáo')),
                ('reporter_phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('reason', models.CharField(choices=[('fraud', 'Tin có dấu hiệu lừa đảo'), ('duplicate', 'Tin trung lặp nội dung'), ('inappropriate', 'Không liên hệ được chủ tin đăng'), ('wrong_info', 'Thông tin không đúng thực tế (giá, diện tích, hình ảnh...)'), ('other', 'Lý do khác')], max_length=50, verbose_name='Lý do báo cáo')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả thêm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian báo cáo')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('reviewing', 'Đang xem xét'), ('resolved', 'Đã xử lý'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('admin_note', models.TextField(blank=True, verbose_name='Ghi chú admin')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='website.rentalpost')),
            ],
            options={
                'verbose_name': 'Báo cáo vi phạm',
                'verbose_name_plural': 'Báo cáo vi phạm',
                'ordering': ['-created_at'],
            },
        ),
    ]
