# Generated by Django 4.2.10 on 2025-11-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_postreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPPackageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('vip1', 'VIP 1'), ('vip2', 'VIP 2'), ('vip3', 'VIP 3')], max_length=8, unique=True, verbose_name='Gói VIP')),
                ('name', models.CharField(default='Gói VIP', max_length=50, verbose_name='Tên gói')),
                ('posts_per_day', models.IntegerField(default=1, verbose_name='Số tin đăng mỗi ngày')),
                ('expire_days', models.IntegerField(default=1, verbose_name='Thời gian hết hạn (ngày)')),
                ('title_color', models.CharField(choices=[('red', 'Màu đỏ'), ('blue', 'Màu xanh'), ('pink', 'Màu hồng')], default='red', max_length=10, verbose_name='Màu tiêu đề')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá gói (VNĐ)')),
                ('stars', models.IntegerField(default=1, help_text='Số sao từ 1-5', verbose_name='Số sao hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Cấu hình gói VIP',
                'verbose_name_plural': 'Cấu hình gói VIP',
                'ordering': ['plan'],
            },
        ),
    ]
