# Generated by Django 4.2.10 on 2025-11-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_vippackageconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='deposit_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='deposit_confirmed_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='deposit_payment_method',
            field=models.CharField(blank=True, choices=[('wallet', 'Ví nội bộ'), ('momo', 'MoMo'), ('vnpay', 'VNPay')], max_length=20),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='deposit_transaction_id',
            field=models.CharField(blank=True, help_text='Mã giao dịch từ cổng thanh toán', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='deposit_status',
            field=models.CharField(choices=[('none', 'Không yêu cầu'), ('requested', 'Đã yêu cầu đặt cọc'), ('paid', 'Đã đặt cọc'), ('cancelled', 'Khách hủy đặt cọc'), ('waived', 'Không cần đặt cọc'), ('pending_payment', 'Đang chờ thanh toán'), ('confirmed_by_owner', 'Chủ đã xác nhận')], default='none', max_length=20),
        ),
    ]
