# Generated by Django 4.2.10 on 2025-11-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_rentalrequest_deposit_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='deposit_payment_url',
            field=models.URLField(blank=True, help_text='Link thanh toán MoMo QR', max_length=500),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='deposit_payment_method',
            field=models.CharField(blank=True, choices=[('wallet', 'Ví nội bộ'), ('momo', 'MoMo')], max_length=20),
        ),
    ]
