# Generated by Django 4.2.10 on 2025-11-05 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0057_rentalrequest_deposit_payment_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(help_text='Số hóa đơn', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, help_text='Số tiền đặt cọc (VNĐ)', max_digits=15)),
                ('post_title', models.CharField(help_text='Tên phòng', max_length=255)),
                ('payment_method', models.CharField(help_text='Phương thức thanh toán', max_length=20)),
                ('transaction_id', models.CharField(help_text='Mã giao dịch', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ngày tạo bill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_bills_as_customer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_bills_as_owner', to=settings.AUTH_USER_MODEL)),
                ('rental_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_bill', to='website.rentalrequest')),
            ],
            options={
                'verbose_name': 'Hóa đơn đặt cọc',
                'verbose_name_plural': 'Hóa đơn đặt cọc',
                'ordering': ['-created_at'],
            },
        ),
    ]
