# Generated by Django 4.2.10 on 2025-11-05 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0058_depositbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_landlord_reviews', to=settings.AUTH_USER_MODEL)),
                ('rental_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_review', to='website.rentalrequest')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_landlord_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['landlord', 'created_at'], name='website_lan_landlor_743cc8_idx')],
            },
        ),
    ]
