# Generated by Django 4.2.10 on 2025-11-05 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0059_landlordreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('post_expired', 'Phòng hết hạn'), ('chat_new', 'Tin nhắn mới'), ('deposit_paid', 'Khách đã đặt cọc'), ('rental_request_new', 'Yêu cầu thuê mới'), ('review_received', 'Khách đã đánh giá bạn'), ('vip_expired', 'Gói VIP hết hạn'), ('vip_payment_success', 'Thanh toán VIP thành công'), ('wallet_topup_success', 'Nạp tiền ví thành công'), ('rental_cancel_requested', 'Khách yêu cầu hủy phòng'), ('deposit_success', 'Đặt cọc thành công'), ('deposit_confirmed', 'Chủ trọ xác nhận đặt cọc'), ('rental_confirmed', 'Xác nhận thuê phòng'), ('chat_reply', 'Chủ trọ phản hồi tin nhắn'), ('rental_request_status', 'Yêu cầu thuê được xử lý')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=512)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.rentalpost')),
                ('rental_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.rentalrequest')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.rechargetransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='website_not_user_id_4ad158_idx'), models.Index(fields=['type', 'created_at'], name='website_not_type_377ef3_idx')],
            },
        ),
    ]
