# Generated by Django 5.2.8 on 2025-11-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_alter_customerprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(choices=[('unset', 'Chưa chọn'), ('customer', 'Khách hàng'), ('owner', 'Chủ trọ')], default='unset', max_length=20),
        ),
    ]
