# Generated by Django 5.2.8 on 2025-11-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_alter_customerprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('owner', 'Chủ trọ')], default='customer', max_length=20),
        ),
    ]
