# Generated by Django 5.2.8 on 2025-11-15 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_customerprofile_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositbill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_bills_as_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='depositbill',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_bills_as_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
