# Generated by Django 5.2.8 on 2025-11-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_alter_depositbill_customer_alter_depositbill_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='auto_removed',
            field=models.BooleanField(default=False, verbose_name='Đã tự động gỡ'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='deadline_fix',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline sửa (24h)'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm gỡ bài'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='warning_sent',
            field=models.BooleanField(default=False, verbose_name='Đã gửi cảnh báo'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='warning_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm gửi cảnh báo'),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='violation_count',
            field=models.IntegerField(default=0, help_text='Tổng số lần bị báo cáo'),
        ),
    ]
