# Generated by Django 5.2.8 on 2025-11-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_postreport_auto_removed_postreport_deadline_fix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionlog',
            name='details',
            field=models.TextField(blank=True, help_text='Chi tiết lý do xóa'),
        ),
    ]
