# Generated by Django 5.2.8 on 2025-11-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_deletionlog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('post_expired', 'Phòng hết hạn'), ('chat_new', 'Tin nhắn mới'), ('deposit_paid', 'Khách đã đặt cọc'), ('rental_request_new', 'Yêu cầu thuê mới'), ('review_received', 'Khách đã đánh giá bạn'), ('vip_expired', 'Gói VIP hết hạn'), ('vip_payment_success', 'Thanh toán VIP thành công'), ('wallet_topup_success', 'Nạp tiền ví thành công'), ('rental_cancel_requested', 'Khách yêu cầu hủy phòng'), ('violation_warning', 'Cảnh báo vi phạm bài đăng'), ('post_removed_violation', 'Bài đăng bị gỡ do vi phạm'), ('deposit_success', 'Đặt cọc thành công'), ('deposit_confirmed', 'Chủ trọ xác nhận đặt cọc'), ('rental_confirmed', 'Xác nhận thuê phòng'), ('chat_reply', 'Chủ trọ phản hồi tin nhắn'), ('rental_request_status', 'Yêu cầu thuê được xử lý')], max_length=40),
        ),
    ]
