# Generated by Django 5.2.8 on 2025-11-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0071_postreport_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
