# Generated by Django 5.2.8 on 2025-11-26 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_rentalpost_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên địa điểm', max_length=255)),
                ('poi_type', models.CharField(choices=[('school', 'Trường học'), ('hospital', 'Bệnh viện'), ('supermarket', 'Siêu thị'), ('bus_station', 'Bến xe'), ('train_station', 'Ga tàu'), ('metro_station', 'Trạm Metro'), ('market', 'Chợ'), ('park', 'Công viên'), ('mall', 'Trung tâm thương mại'), ('bank', 'Ngân hàng'), ('atm', 'ATM'), ('pharmacy', 'Nhà thuốc'), ('restaurant', 'Nhà hàng'), ('cafe', 'Quán cà phê'), ('gym', 'Phòng gym'), ('other', 'Khác')], default='other', max_length=50)),
                ('latitude', models.FloatField(blank=True, help_text='Vĩ độ', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Kinh độ', null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.province')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.ward')),
            ],
            options={
                'verbose_name': 'Điểm quan tâm (POI)',
                'verbose_name_plural': 'Các điểm quan tâm (POI)',
                'indexes': [models.Index(fields=['poi_type', 'is_active'], name='website_poi_poi_typ_fc3c1d_idx')],
            },
        ),
    ]
