# Generated by Django 5.2.8 on 2025-12-11 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_chatmessage_image_alter_chatmessage_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Admin đã từ chối tin'),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalpost',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Lý do từ chối tin'),
        ),
    ]
