# Generated by Django 4.2.10

from django.db import migrations


def enable_pgvector(apps, schema_editor):
    """Try to enable pgvector extension, silently fail if not installed."""
    if schema_editor.connection.vendor != 'postgresql':
        return

    # Use raw connection to avoid transaction issues
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")
        except Exception:
            # pgvector not installed, skip (will use JSON fallback)
            # Rollback the failed statement
            schema_editor.connection.connection.rollback()


def disable_pgvector(apps, schema_editor):
    """Reverse migration: drop extension."""
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute("DROP EXTENSION IF EXISTS vector;")
        except Exception:
            schema_editor.connection.connection.rollback()


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(enable_pgvector, reverse_code=disable_pgvector),
    ]
