# Generated by Django 4.2.10 on 2025-11-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('kind', models.CharField(db_index=True, max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('text_snippet', models.TextField()),
                ('embedding_pgvector', models.BinaryField(blank=True, null=True)),
                ('embedding_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'doc_id'], name='chatbot_vec_kind_54af20_idx')],
            },
        ),
    ]
