# Generated by Django 5.2.8 on 2025-11-25 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_vectordocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('message', models.TextField(help_text='Tin nhắn được đánh giá')),
                ('response', models.TextField(help_text='Câu trả lời được đánh giá')),
                ('rating', models.CharField(choices=[('positive', '👍 Hữu ích'), ('negative', '👎 Không hữu ích')], max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Góp ý từ người dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnansweredQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Câu hỏi người dùng')),
                ('bot_response', models.TextField(help_text='Câu trả lời của bot (để đánh giá)')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved', models.BooleanField(default=False, help_text='Đã thêm vào FAQ?')),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của admin')),
                ('frequency', models.IntegerField(default=1, help_text='Số lần câu hỏi tương tự')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved', '-created_at'], name='chatbot_una_resolve_b078ad_idx')],
            },
        ),
    ]
