"""
Django settings for PhongTro project.

Generated by 'django-admin startproject' using Django 4.2.10.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^4b85rgt15a02oso0h5-e_4a%b!u#i6q(v=%geh0@$&9qcsn_%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Cần cho allauth
    # 'django.contrib.gis',  # GeoDjango for mapping - Tạm tắt vì chưa có GDAL
    'channels',
    'website.apps.WebsiteConfig',
    'chatbot',
    'goiy_ai',  # Hệ thống gợi ý AI
    "widget_tweaks",
    "django.contrib.humanize",
    # django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # Google OAuth
]

MIDDLEWARE = [
    'PhongTro.middleware.separate_session.SeparateSessionMiddleware',  # Đã fix - chỉ ghi nhận visit
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Cần cho django-allauth
    'PhongTro.middleware.check_social_login.CheckSocialLoginMiddleware',  # Kiểm tra và redirect user đăng nhập Google
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'website.middleware.ExpiredPostNotificationMiddleware',  # Tự động gửi email khi bài hết hạn
]

ROOT_URLCONF = 'PhongTro.urls'
SESSION_COOKIE_NAME = 'user_sessionid'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # Cần cho allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'website.context_processors.admin_dashboard_stats',
                'website.context_processors.footer_data',
                'website.context_processors.ai_moderation_alerts',
                'website.context_processors.vip_status',
                'website.context_processors.notifications_context',
                'website.context_processors.unread_messages_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'PhongTro.wsgi.application'
ASGI_APPLICATION = 'PhongTro.asgi.application'

# Channels configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Tạm dùng postgresql, sau khi cài GDAL đổi thành postgis
        'NAME': 'phongtro',        # Tên database trong PostgreSQL
        'USER': 'postgres',        # User PostgreSQL
        'PASSWORD': '123456',      # Mật khẩu
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Caching để tăng tốc
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'phongtro-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Django sẽ tìm static trong website/static/
STATICFILES_DIRS = [
    BASE_DIR / 'website/static'
]

# Media files (upload ảnh)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver']

# Email settings
# If EMAIL_HOST_USER is provided in environment, use SMTP; otherwise fallback to console backend
# 🔧 CẤU HÌNH GMAIL: Set trong environment variables hoặc .env file
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  # App Password
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Chỉ dùng SMTP nếu có đầy đủ thông tin và email là Gmail
# Nếu email không phải Gmail, cần cấu hình SMTP server phù hợp
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    # Kiểm tra xem email có phải Gmail không
    is_gmail = EMAIL_HOST_USER.endswith('@gmail.com') or EMAIL_HOST_USER.endswith('@googlemail.com')

    if is_gmail:
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
        EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
        EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '1') == '1'
        EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', '0') == '1'
        DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
    else:
        # Email không phải Gmail → dùng console backend để tránh lỗi
        # Hoặc cấu hình SMTP server phù hợp với domain email của bạn
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
        print(f"⚠️ Email {EMAIL_HOST_USER} không phải Gmail. Đang dùng console backend.")
        print("💡 Để gửi email thật, vui lòng:")
        print("   1. Tìm SMTP server của domain @student.tdmu.edu.vn")
        print("   2. Hoặc dùng Gmail và tạo App Password")
        print("   3. Cấu hình EMAIL_HOST, EMAIL_PORT phù hợp")

SITE_URL = 'http://127.0.0.1:8000'
# MoMo sandbox / payment gateway settings (use env vars in production)
MOMO_PARTNER_CODE = os.environ.get('MOMO_PARTNER_CODE', 'MOMO')
MOMO_ACCESS_KEY   = os.environ.get('MOMO_ACCESS_KEY', 'F8BBA842ECF85')
MOMO_SECRET_KEY   = os.environ.get('MOMO_SECRET_KEY', 'K951B6PE1waDMi640xX08PD3vg6EkVlz')
MOMO_ENDPOINT     = os.environ.get('MOMO_ENDPOINT', 'https://test-payment.momo.vn/v2/gateway/api/create')

MOMO_NOTIFY_URL   = os.environ.get('MOMO_NOTIFY_URL', SITE_URL + '/payments/momo/notify/')
MOMO_RETURN_URL   = os.environ.get('MOMO_RETURN_URL', SITE_URL + '/payments/momo/return/')
# ZaloPay sandbox / payment gateway settings (use env vars in production)
# ZaloPay settings removed per request

# VNPAY sandbox settings (from merchant test inbox)
VNPAY_TMN_CODE = os.environ.get('VNPAY_TMN_CODE', '4LP6YID1')
VNPAY_HASH_SECRET = os.environ.get('VNPAY_HASH_SECRET', '6BLUIBHAUOBRUMTAVCPQ1NDJ2IS91E2Z')
# URL provided in email - normalize to a working default for sandbox
VNPAY_CREATE_URL = os.environ.get('VNPAY_CREATE_URL', 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html')
VNPAY_PAYMENT_URL = VNPAY_CREATE_URL  # Alias for compatibility
VNPAY_RETURN_URL = os.environ.get('VNPAY_RETURN_URL', SITE_URL + '/payments/vnpay/return/')
VNPAY_NOTIFY_URL = os.environ.get('VNPAY_NOTIFY_URL', SITE_URL + '/payments/vnpay/notify/')

# ===== AI Recommendation toggles =====
# Force using Content-based only (tạm thời tắt CF/ML)
AI_FORCE_CONTENT_ONLY = True

# ===== Grop (Groq) AI Chatbot Configuration =====
# IMPORTANT: Set GROP_API_KEY in environment variables or .env file
GROP_API_KEY = os.environ.get('GROP_API_KEY', '')  # ⚠️ DO NOT hardcode API keys!
GROP_MODEL = os.environ.get('GROP_MODEL', 'llama-3.3-70b-versatile')
GROP_TEMPERATURE = float(os.environ.get('GROP_TEMPERATURE', '0.7'))
GROP_MAX_TOKENS = int(os.environ.get('GROP_MAX_TOKENS', '2048'))

# ===== django-allauth Configuration =====
# Site ID (cần cho allauth)
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Django default
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth
]

# Allauth settings
# Sử dụng cấu hình mới (Django 5.x) thay vì deprecated settings
ACCOUNT_LOGIN_METHODS = {'email'}  # Thay cho ACCOUNT_AUTHENTICATION_METHOD
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # Thay cho ACCOUNT_EMAIL_REQUIRED và ACCOUNT_USERNAME_REQUIRED
ACCOUNT_EMAIL_VERIFICATION = 'none'  # 'none', 'mandatory', 'optional'
ACCOUNT_UNIQUE_EMAIL = True
# Lưu ý: ACCOUNT_USER_MODEL_USERNAME_FIELD = None có nghĩa là không yêu cầu username khi đăng ký
# Nhưng Django User model vẫn cần username, nên adapter sẽ tự động tạo username từ email
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'

# Social account settings (Google OAuth)
# Lưu ý: Credentials được lưu trong Django Admin > Social applications
# Nếu đã cấu hình trong Admin, không cần phần APP ở đây
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        # APP credentials sẽ được lấy từ database (Django Admin > Social applications)
        # Hoặc set trong environment variables:
        # GOOGLE_CLIENT_ID và GOOGLE_CLIENT_SECRET
    }
}

# Redirect sau khi đăng nhập/đăng ký
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
SOCIALACCOUNT_LOGIN_ON_GET = True  # Bỏ qua trang xác nhận, đăng nhập trực tiếp

# Custom adapter để redirect đến trang chọn role sau khi đăng nhập Google lần đầu
ACCOUNT_ADAPTER = 'PhongTro.account_adapter.CustomAccountAdapter'
# Custom social account adapter để tự động tạo username
SOCIALACCOUNT_ADAPTER = 'PhongTro.socialaccount_adapter.CustomSocialAccountAdapter'

