# Generated by Django 4.2.10 on 2025-10-30 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0054_postreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('recommended_posts', models.JSONField(help_text='Danh sách ID các bài được gợi ý')),
                ('algorithm_used', models.CharField(help_text='Thuật toán được dùng (content/collaborative/hybrid)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_posts', models.JSONField(default=list, help_text='Các bài user đã click từ gợi ý')),
                ('conversion_rate', models.FloatField(default=0.0, help_text='Tỷ lệ click/impression')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log gợi ý',
                'verbose_name_plural': 'Log gợi ý',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('interaction_type', models.CharField(choices=[('view', 'Xem chi tiết'), ('save', 'Lưu tin'), ('unsave', 'Bỏ lưu tin'), ('contact', 'Liên hệ'), ('request', 'Gửi yêu cầu thuê'), ('share', 'Chia sẻ')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Thông tin trình duyệt')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to='website.rentalpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tương tác người dùng',
                'verbose_name_plural': 'Tương tác người dùng',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='goiy_ai_use_user_id_169462_idx'), models.Index(fields=['post', 'created_at'], name='goiy_ai_use_post_id_91e872_idx'), models.Index(fields=['session_id', 'created_at'], name='goiy_ai_use_session_635d10_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session ID cho user chưa đăng nhập', max_length=100)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('min_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('min_area', models.FloatField(blank=True, null=True)),
                ('max_area', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='Danh sách features được chọn')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('results_count', models.IntegerField(default=0, help_text='Số kết quả tìm thấy')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.province')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử tìm kiếm',
                'verbose_name_plural': 'Lịch sử tìm kiếm',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['user', 'searched_at'], name='goiy_ai_sea_user_id_7f160e_idx'), models.Index(fields=['session_id', 'searched_at'], name='goiy_ai_sea_session_5f4bc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session ID cho user chưa đăng nhập', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0, help_text='Thời gian xem (giây)')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_views', to='website.rentalpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_post_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='goiy_ai_pos_user_id_fbd748_idx'), models.Index(fields=['post', 'viewed_at'], name='goiy_ai_pos_post_id_16dd5d_idx'), models.Index(fields=['session_id', 'viewed_at'], name='goiy_ai_pos_session_6adc9f_idx')],
            },
        ),
    ]
