# Generated by Django 4.2.10 on 2025-10-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goiy_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='search_type',
            field=models.CharField(blank=True, default='manual', help_text='manual/recommendation_tab/filter/etc', max_length=50),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Thông tin trình duyệt'),
        ),
    ]
